### ISSUE TITLE
Confused metadata while tailing kubernetes containers logs

### ISSUE THREAD

**Issue by gerasym** [fluent/fluent-bit-kubernetes-daemonset#3] opened 2017-06-16 09:13 UTC
Logs from /var/log/containers/**service-1**.log were enriched with metadata from /var/log/containers/**service-2**.log
This bug reproduces after fluent-bit restart.

**Kubernetes v.1.6
Docker version 1.12.0, build 8eab29e
Ubuntu 16.04 LTS
Fluent-bit container fluent/fluent-bit-kubernetes-daemonset:0.11
Elasticsearch container docker.elastic.co/elasticsearch/elasticsearch:5.4.0**

Kubernetes deployment configuration:
> apiVersion: extensions/v1beta1
> kind: DaemonSet
> metadata:
>   name: fluent-bit
>   namespace: kube-system
>   labels:
>     k8s-app: fluent-bit-logging
>     version: v1
>     kubernetes.io/cluster-service: "true"
> spec:
>   template:
>     metadata:
>       labels:
>         k8s-app: fluent-bit-logging
>         version: v1
>         kubernetes.io/cluster-service: "true"
>     spec:
>       serviceAccount: fluent
>       serviceAccountName: fluent
>       containers:
>       - name: fluent-bit
>         image: docker.company.com/fluent-bit-debug:0.11
>         imagePullPolicy: Always
>         env:
>           - name:  FLUENT_ELASTICSEARCH_HOST
>             value: "10.10.7.21"
>           - name:  FLUENT_ELASTICSEARCH_PORT
>             value: "9200"
>         resources:
>           limits:
>             memory: 100Mi
>           requests:
>             cpu: 100m
>             memory: 100Mi
>         volumeMounts:
>         - name: varlog
>           mountPath: /var/log
>         - name: varlibdockercontainers
>           mountPath: /var/lib/docker/containers
>           readOnly: true
>       terminationGracePeriodSeconds: 10
>       volumes:
>       - name: varlog
>         hostPath:
>           path: /var/log
>       - name: varlibdockercontainers
>         hostPath:
>           path: /var/lib/docker/containers

> apiVersion: rbac.authorization.k8s.io/v1beta1
> kind: ClusterRole
> metadata:
>   name: fluent
>   namespace: kube-system
> rules:
> - apiGroups:
>   - ""
>   resources:
>   - pods
>   verbs:
>   - get
>   - list
>   - watch

**fluent-bit.conf**
> [SERVICE]
>     Flush          1
>     Daemon         Off
>     Log_Level      debug
>     Parsers_File   parsers.conf
> 
> [INPUT]
>     Name           tail
>     Tag            kube.*
>     Path           /var/log/containers/*.log
>     Exclude_Path   /var/log/containers/*fluent*.log,/var/log/containers/*calico*.log
>     Parser         docker
>     DB             /var/log/flb_kube.db
>     Mem_Buf_Limit  5MB
> 
> [FILTER]
>     Name           kubernetes
>     Match          kube.*
>     Kube_URL       https://kubernetes.default.svc:443
>     Merge_JSON_Log On
> 
> [OUTPUT]
>     Name   es
>     Match  *
>     Host   ${FLUENT_ELASTICSEARCH_HOST}
>     Port   ${FLUENT_ELASTICSEARCH_PORT}
>     Logstash_Format On
>     Retry_Limit False

**Log in elasticsearch**

> {
>   "_index": "logstash-2017.06.16",
>   "_type": "flb_type",
>   "_id": "AVyv0PEQkGtdARlOstLQ",
>   "_version": 1,
>   "_score": null,
>   "_source": {
>     "@timestamp": "2017-06-16T07:31:39Z",
>     "log": "{\"levelname\": \"DEBUG\", \"module\": \"containers\", \"lineno\": 177, \"request_id\": null, \"args\": [\"<ServiceContainer [profiles_service] at 0x7f69e8227048>\"], \"msg\": \"starting %s\"}\n",
>     "stream": "stderr",
>     "time": "2017-06-16T07:31:39.745970396Z",
>     "levelname": "DEBUG",
>     "module": "containers",
>     "lineno": 177,
>     "request_id": null,
>     "args": [
>       "u003cServiceContainer [profiles_service] at 0x7f69e8227048u003e"
>     ],
>     "msg": "starting %s",
>     "kubernetes": {
>       "pod_name": "auth-emul-3229163131-xtfvw",
>       "namespace_name": "pandora",
>       "container_name": "auth-emul",
>       "docker_id": "3dbb153b9254ad292a459d84cab6936ed053b3f90d1c485035b2038bf9d9957c",
>       "pod_id": "ca96a54c-5265-11e7-826e-724e14304815",
>       "labels": {
>         "app": "auth-emul",
>         "pod-template-hash": "3229163131"
>       },
>       "annotations": {
>         "kubernetes_io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"pandora\",\"name\":\"auth-emul-3229163131\",\"uid\":\"ca9617a7-5265-11e7-826e-724e14304815\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"3343079\"}}\n"
>       }
>     }
>   },
>   "fields": {
>     "@timestamp": [
>       1497598299000
>     ],
>     "time": [
>       1497598299745
>     ]
>   },
>   "highlight": {
>     "kubernetes.container_name": [
>       "@kibana-highlighted-field@auth@/kibana-highlighted-field@-@kibana-highlighted-field@emul@/kibana-highlighted-field@"
>     ],
>     "kubernetes.namespace_name": [
>       "@kibana-highlighted-field@pandora@/kibana-highlighted-field@"
>     ]
>   },
>   "sort": [
>     1497598299745
>   ]
> }

**Comment by edsiper** [comment] 2017-06-16 14:43
I've tried to reproduce the problem that you stated but it was impossible because of the following reasons:

- the in_tail plugin (per configuration) will try to expand the tag with the file name being monitored, note that the filename must contains the following relevant information (this is done by Docker engine actually):
  - pod_name
  - namespace_name
  - container_name
  - docker_id

In the case of a file named __/var/log/containers/service-1.log__ the filter will not touch the original log entry. 

If service-1.log is just an example name, please let me know the real name of the files so I can try to reproduce locally (if you have specific steps to reproduce would be appreciated)

**Comment by gerasym** [comment] 2017-06-19 07:55
My fault,

Actual log names are  **/var/log/containers/profiles-3207024224-q0985_pandora_profiles-9614b2f8d1579348a095990b862e2705ed033b380a86d044d594231a1b796125.log**
and looks like 
**/var/log/containers/auth-emul-3229163131-whb23_pandora_auth-emul-bb7308380039de4c765c2176fa74b012b2a1a8d27d1037217c08cdb7c310aadb.log**

Log line:

> {"log":"{\"levelname\": \"DEBUG\", \"module\": \"containers\", \"lineno\": 177, \"request_id\": null, \"args\": [\"\u003cServiceContainer [profiles_service] at 0x7f69e8227048\u003e\"], \"msg\": \"starting %s\"}\n","stream":"stderr","time":"2017-06-16T07:31:39.745970396Z"}

from 1st log file made it's way to elastic like it was taken from 2nd log file.

**Comment by edsiper** [comment] 2017-06-19 15:00
@gerasym Thanks, please review the steps below:

### Troubleshooting info

- [POD 1 Regex data](http://rubular.com/r/JTMRZsxZJU)
- [POD 2 Regex data](http://rubular.com/r/7nW3FYeL3W)

### Next steps

In order to determinate the root cause of the problem, would you please run the following steps and provide the output of each command ?

__1__ Run Kubectl Proxy:

```
$ kubectl proxy
```

> with the proxy enabled we can access the API server without restrictions

__2__ Gather metadata for POD profiles-3207024224-q0985

```
$ curl -i http://127.0.0.1:8001/api/v1/namespaces/pandora/pods/profiles-3207024224-q0985
```

__3__ Gather metadata por POD auth-emul-3229163131-whb23

```
$ curl -i http://127.0.0.1:8001/api/v1/namespaces/pandora/pods/auth-emul-3229163131-whb23
```

**Comment by edsiper** [comment] 2017-11-02 22:04
This is a known issues that was addressed a while ago. Closing as fixed.

**Closed by edsiper** 2017-11-02 22:04 UTC
